# Some Teams One Dream
Hand checking NBA teams from the 2014-2018 seasons

In [2]:
#importing libraries 
import pandas as pd

In [3]:
#uploading the nba csv and saving it as a dataframe called nba
nba = pd.read_csv('nba.games.stats.csv')

In [4]:
#sneak peak into the data
nba.head()

,Unnamed: 0,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,ATL,1,2014-10-29,Away,TOR,L,102,109,40,...,27,33,0.818,16,48,26,13,9,9,22
1,2,ATL,2,2014-11-01,Home,IND,W,102,92,35,...,18,21,0.857,11,44,25,5,5,18,26
2,3,ATL,3,2014-11-05,Away,SAS,L,92,94,38,...,27,38,0.711,11,50,25,7,9,19,15
3,4,ATL,4,2014-11-07,Away,CHO,L,119,122,43,...,20,27,0.741,11,51,31,6,7,19,30
4,5,ATL,5,2014-11-08,Home,NYK,W,103,96,33,...,8,11,0.727,13,44,26,2,6,15,29

In [5]:
#checking to see how many rows and columns there are
nba.shape

(9840, 41)

In [6]:
#checking data types, null values, and column names
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9840 entries, 0 to 9839
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                9840 non-null   int64
 1   Team                      9840 non-null   object
 2   Game                      9840 non-null   int64
 3   Date                      9840 non-null   object
 4   Home                      9840 non-null   object
 5   Opponent                  9840 non-null   object
 6   WINorLOSS                 9840 non-null   object
 7   TeamPoints                9840 non-null   int64
 8   OpponentPoints            9840 non-null   int64
 9   FieldGoals                9840 non-null   int64
 10  FieldGoalsAttempted       9840 non-null   int64
 11  FieldGoals.               9840 non-null   float64
 12  X3PointShots              9840 non-null   int64
 13  X3PointShotsAttempted     9840 non-null   int64
 14  X3PointShots.             9840 non-null   float64
 15  FreeThrows                9840 non-null   int64
 16  FreeThrowsAttempted       9840 non-null   int64
 17  FreeThrows.               9840 non-null   float64
 18  OffRebounds               9840 non-null   int64
 19  TotalRebounds             9840 non-null   int64
 20  Assists                   9840 non-null   int64
 21  Steals                    9840 non-null   int64
 22  Blocks                    9840 non-null   int64
 23  Turnovers                 9840 non-null   int64
 24  TotalFouls                9840 non-null   int64
 25  Opp.FieldGoals            9840 non-null   int64
 26  Opp.FieldGoalsAttempted   9840 non-null   int64
 27  Opp.FieldGoals.           9840 non-null   float64
 28  Opp.3PointShots           9840 non-null   int64
 29  Opp.3PointShotsAttempted  9840 non-null   int64
 30  Opp.3PointShots.          9840 non-null   float64
 31  Opp.FreeThrows            9840 non-null   int64
 32  Opp.FreeThrowsAttempted   9840 non-null   int64
 33  Opp.FreeThrows.           9840 non-null   float64
 34  Opp.OffRebounds           9840 non-null   int64
 35  Opp.TotalRebounds         9840 non-null   int64
 36  Opp.Assists               9840 non-null   int64
 37  Opp.Steals                9840 non-null   int64
 38  Opp.Blocks                9840 non-null   int64
 39  Opp.Turnovers             9840 non-null   int64
 40  Opp.TotalFouls            9840 non-null   int64
dtypes: float64(6), int64(30), object(5)
memory usage: 3.1+ MB

In [7]:
#looking at the summary statistics of all the numeric columns
nba.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,9840.0,11960.157012,18654.867508,1.000,2537.750,5141.500,7715.250,82119.000
Game,9840.0,41.500000,23.670804,1.000,21.000,41.500,62.000,82.000
TeamPoints,9840.0,103.652337,12.188043,64.000,95.000,103.000,112.000,149.000
OpponentPoints,9840.0,103.652337,12.188043,64.000,95.000,103.000,112.000,149.000
FieldGoals,9840.0,38.602439,5.029992,19.000,35.000,38.000,42.000,58.000
FieldGoalsAttempted,9840.0,84.902439,7.130043,60.000,80.000,85.000,89.000,129.000
FieldGoals.,9840.0,0.455689,0.054711,0.271,0.418,0.455,0.494,0.684
X3PointShots,9840.0,9.126829,3.598084,0.000,7.000,9.000,11.000,25.000
X3PointShotsAttempted,9840.0,25.623679,7.102501,4.000,21.000,25.000,30.000,61.000
X3PointShots.,9840.0,0.354321,0.097782,0.000,0.290,0.353,0.419,0.750
FreeThrows,9840.0,17.320630,6.002620,1.000,13.000,17.000,21.000,44.000
FreeThrowsAttempted,9840.0,22.749390,7.390451,1.000,18.000,22.000,27.000,64.000
FreeThrows.,9840.0,0.762395,0.104297,0.143,0.696,0.769,0.833,1.000
OffRebounds,9840.0,10.287602,3.807120,0.000,8.000,10.000,13.000,38.000
TotalRebounds,9840.0,43.520630,6.410428,20.000,39.000,43.000,48.000,81.000
Assists,9840.0,22.546545,5.122989,6.000,19.000,22.000,26.000,47.000
Steals,9840.0,7.750508,2.958886,0.000,6.000,8.000,10.000,21.000
Blocks,9840.0,4.827642,2.536845,0.000,3.000,5.000,6.000,18.000
Turnovers,9840.0,13.638618,3.869543,2.000,11.000,13.000,16.000,29.000
TotalFouls,9840.0,20.058537,4.317611,7.000,17.000,20.000,23.000,42.000
Opp.FieldGoals,9840.0,38.602439,5.029992,19.000,35.000,38.000,42.000,58.000
Opp.FieldGoalsAttempted,9840.0,84.902439,7.130043,60.000,80.000,85.000,89.000,129.000
Opp.FieldGoals.,9840.0,0.455689,0.054711,0.271,0.418,0.455,0.494,0.684
Opp.3PointShots,9840.0,9.126829,3.598084,0.000,7.000,9.000,11.000,25.000
Opp.3PointShotsAttempted,9840.0,25.623679,7.102501,4.000,21.000,25.000,30.000,61.000
Opp.3PointShots.,9840.0,0.354321,0.097782,0.000,0.290,0.353,0.419,0.750
Opp.FreeThrows,9840.0,17.320630,6.002620,1.000,13.000,17.000,21.000,44.000
Opp.FreeThrowsAttempted,9840.0,22.749390,7.390451,1.000,18.000,22.000,27.000,64.000
Opp.FreeThrows.,9840.0,0.762395,0.104297,0.143,0.696,0.769,0.833,1.000
Opp.OffRebounds,9840.0,10.287602,3.807120,0.000,8.000,10.000,13.000,38.000
Opp.TotalRebounds,9840.0,43.520630,6.410428,20.000,39.000,43.000,48.000,81.000
Opp.Assists,9840.0,22.546545,5.122989,6.000,19.000,22.000,26.000,47.000
Opp.Steals,9840.0,7.750508,2.958886,0.000,6.000,8.000,10.000,21.000
Opp.Blocks,9840.0,4.827642,2.536845,0.000,3.000,5.000,6.000,18.000
Opp.Turnovers,9840.0,13.638618,3.869543,2.000,11.000,13.000,16.000,29.000
Opp.TotalFouls,9840.0,20.058537,4.317611,7.000,17.000,20.000,23.000,42.000

In [8]:
#deleting an unnecessary row to the data
#appears to be the prior index
del nba['Unnamed: 0']

In [9]:
#confirming the deleted column
nba

,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,ATL,1,2014-10-29,Away,TOR,L,102,109,40,80,...,27,33,0.818,16,48,26,13,9,9,22
1,ATL,2,2014-11-01,Home,IND,W,102,92,35,69,...,18,21,0.857,11,44,25,5,5,18,26
2,ATL,3,2014-11-05,Away,SAS,L,92,94,38,92,...,27,38,0.711,11,50,25,7,9,19,15
3,ATL,4,2014-11-07,Away,CHO,L,119,122,43,93,...,20,27,0.741,11,51,31,6,7,19,30
4,ATL,5,2014-11-08,Home,NYK,W,103,96,33,81,...,8,11,0.727,13,44,26,2,6,15,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,WAS,78,2018-04-03,Away,HOU,L,104,120,38,72,...,18,27,0.667,10,46,26,13,3,9,14
9836,WAS,79,2018-04-05,Away,CLE,L,115,119,47,94,...,22,28,0.786,5,35,26,10,3,16,14
9837,WAS,80,2018-04-06,Home,ATL,L,97,103,35,87,...,16,23,0.696,7,50,24,5,5,18,22
9838,WAS,81,2018-04-10,Home,BOS,W,113,101,41,83,...,22,27,0.815,13,44,22,14,1,16,18
9839,WAS,82,2018-04-11,Away,ORL,L,92,101,33,95,...,22,27,0.815,6,42,20,6,7,16,27

- season one w/l column

In [27]:
nba_records14_15 = nba.loc[:2459,:].groupby('Team').WINorLOSS.value_counts()

In [28]:
nba_records14_15

Team  WINorLOSS
ATL   W            60
      L            22
BOS   L            42
      W            40
BRK   L            44
      W            38
CHI   W            50
      L            32
CHO   L            49
      W            33
CLE   W            53
      L            29
DAL   W            50
      L            32
DEN   L            52
      W            30
DET   L            50
      W            32
GSW   W            67
      L            15
HOU   W            56
      L            26
IND   L            44
      W            38
LAC   W            56
      L            26
LAL   L            61
      W            21
MEM   W            55
      L            27
MIA   L            45
      W            37
MIL   L            41
      W            41
MIN   L            66
      W            16
NOP   W            45
      L            37
NYK   L            65
      W            17
OKC   W            45
      L            37
ORL   L            57
      W            25
PHI   L            64
      W            18
PHO   L            43
      W            39
POR   W            51
      L            31
SAC   L            53
      W            29
SAS   W            55
      L            27
TOR   W            49
      L            33
UTA   L            44
      W            38
WAS   W            46
      L            36
Name: WINorLOSS, dtype: int64

- western conference
    - Los Angeles Lakers or LAL
    - Los Angeles Clippers or LAC
    - Denver Nuggets or DEN
    - Houston Rockets or HOU
    - Oklahoma City Thunder or OKC
    - Utah Jazz or UTA
    - Dallas Mavericks or DAL
    - Portland Trail Blazers or POR
    - Memphis Grizzlies or MEM
    - Phoenix Suns or PHO
    - San Antonio Spurs or SAS
    - Sacramento Kings or SAC
    - New Orleans Pelicans or NOP
    - Minnesota Timberwolves or MIN
    - Golden State Warriors or GSW

- eastern confere
- Milwaukee Bucks as MIL
- Toronto Raptors as TOR
- Boston Celtics as BOS
- Indiana Pacers as IND
- Miami Heat as MIA
- Philadelphia as PHI
- Brooklyn Nets as BRK
- Orlando Magic as ORL
- Washington Wizards as WAS
- Charlotte Hornets as CHO
- Chicago Bulls as CHI
- New York Knicks as NYK
- Detroit Pistons as DET
- Atlanta Hawks as ATL
- Cleveland Cavaliers as CLE